Feature/18 logging deleted messages
actisPRO/Watchdog pull request #26
Opened 2023-03-28 17:42 UTC by Waff3n

2023-03-28 21:30 UTC, Waff3n commented
Move this to service
Invoke sender logic from Handler

2023-03-29 04:11 UTC, actisPRO requested changes

2023-03-29 04:11 UTC, actisPRO commented on Watchdog.Bot/Listeners/MessageListener.cs
> +            int i = 1;
Предлагаю переименовать во что-то типа currentAttachment - код будет читабельнее на мой взгляд

2023-03-29 04:11 UTC, actisPRO commented on Watchdog.Bot/Listeners/MessageListener.cs
> +    public async Task ClientOnMessageDeleteReceived(DiscordClient client, MessageDeleteEventArgs args)
1) предлагаю разделить на короткие методы под каждую логическую задачу (например, создать сообщение лога, обработать вложения, создать эмбед под аттачмент). Это сделает код более читабельным в будущем и упростит тестирование и отладку (и добавить возможность переиспользования кода без копипасты).

2) предлагаю вынести логику в отдельный класс сервиса (например, DeletedMessageLogService). Это упростит тестирование (не нужно будет создавать инстанс этого класса, который требует DiscordClient в конструкторе и регистрацию ивента через RegisterEvents).

2023-03-29 04:11 UTC, actisPRO commented on Watchdog.Bot/Listeners/MessageListener.cs
> +namespace Watchdog.Bot.Listeners;
почему новый неймспейс?) лучше перенести обратно в Watchdog.Bot.Events и переименовать класс в DeletedMessageEventManager (раз уже такая конвенция имен используется)

2023-03-29 07:29 UTC, Waff3n commented on Watchdog.Bot/Listeners/MessageListener.cs
> +            .AddField("**Автор**", $"**{args.Message.Author.Username}** ({args.Message.Author.Mention})", true)
Пинги из эмбэдов не доходят до людей, поэтому можно спокойно упоминать.

2023-03-29 13:20 UTC, actisPRO requested changes

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Services/MessageLogService.cs
> +        var deleteLog = (await guild.GetAuditLogsAsync(action_type: AuditLogActionType.MessageDelete)).OfType<DiscordAuditLogMessageEntry?>().FirstOrDefault(x => x != null && x.Target.Id == message.A
это все ещё может вернуть null: https://learn.microsoft.com/cs-cz/dotnet/api/system.linq.enumerable.firstordefault?view=net-7.0

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Services/MessageLogService.cs
> +    public async Task ClientOnMessageUpdateReceived(DiscordClient client, DiscordGuild guild, DiscordMessage message, DiscordMessage messageAfter, ulong messageLogsChannelId)
client не используется

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Services/MessageLogService.cs
> +    public async Task ClientOnMessagesBulkDeleteReceived(DiscordClient client, DiscordGuild guild, IReadOnlyList<DiscordMessage> messages, ulong messageLogsChannelId)
аналогично название

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Services/MessageLogService.cs
> +    public async Task ClientOnMessagesBulkDeleteReceived(DiscordClient client, DiscordGuild guild, IReadOnlyList<DiscordMessage> messages, ulong messageLogsChannelId)
client не используется

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Events/MessageEventManager.cs
> +public class MessageEventManager : BaseEventManager
лучше добавлять sealed модификатор к классам, у которых не планируется наследование

2023-03-29 13:20 UTC, actisPRO commented on Watchdog.Bot/Services/MessageLogService.cs
> +public class MessageLogService : IMessageLogService
лучше добавлять sealed модификатор к классам, у которых не планируется наследование

2023-03-29 16:21 UTC, actisPRO approved these changes

2023-03-29 16:21 UTC, merged